[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "numax_proxies"
version = "0.2.0"
description = "A Python tool to compute νmax proxies for solar-like oscillators."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Johannes Jørgensen", email = "johannes.joergensen@uibk.ac.at" }
]
urls = { Homepage = "https://github.com/Johanneshj/numax_proxies" }

dependencies = [
    "numpy>=2.0",
    "scipy>=1.12",
    "matplotlib>=3.8",
    "lightkurve>=2.4",
    "pandas>=2.2",
    "astropy>=6.0",
    "finufft>=2.2",
    "pyarrow>=25.0.0",
    "nifty-ls @ git+https://github.com/flatironinstitute/nifty-ls.git@main",
]

[tool.setuptools.packages.find]
where = ["."]